global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'cqrs-order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:9090']    # internal management port
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*):\d+'
        replacement: '${1}'
